#!/bin/sh

MAILINGLIST=./english-names

for n in `cat $MAILINGLIST` ; do
	eval `echo $n | awk -F':' '{ print $1 " " $2}' |\
	sed 's/^\(.*\) \(.*\)$/NAME=\1 ADDRESS=\2/'`

(echo "$NAME:"
 echo ""
 echo "Here you have our end-of-2021 letter:"
 echo ""
 echo "https://jnamaral.github.io/end-of-year-letter-2020/2021/index.html"
 echo ""
 echo "We hope that your year is starting well."
 echo ""
 echo "		Cheers,"
 echo ""
 echo "				Nelson, Scott & Daniel"
 echo ""
 echo "           /     "
 echo "    \     /  /   Jose Nelson Amaral - jamaral@ualberta.ca"
 echo "     )   /  (    Professor"
 echo "    /   /    \   Dept. of Computing Science - University of Alberta"
 echo "   (   /      )  Edmonton, Alberta, Canada, T6G 2E8"
 echo "    \ O      /   Fax: (780)492-1071"
 echo "     \      /    http://www.cs.ualberta.ca/~amaral"
 echo "       ---- "
 echo "") | Mail -r "jamaral@ualberta.ca" -s "End-of-2021 Blog" $ADDRESS
 done
