#!/bin/sh

MAILINGLIST=./portuguese-names

for n in `cat $MAILINGLIST` ; do
	eval `echo $n | awk -F':' '{ print $1 " " $2}' |\
	sed 's/^\(.*\) \(.*\)$/NAME=\1 ADDRESS=\2/'`

(echo "$NAME:"
 echo ""
 echo "Acabei de escrever o nosso blog de final de ano para 2022:"
 echo "" 
 echo "https://jnamaral.github.io/end-of-year-letter-2020/2022/fim-de-2022.html"
 echo ""
 echo "Tudo de bom no novo ano."
 echo ""
 echo "		Cheers,"
 echo ""
 echo "				Nelson, Scott & Daniel"
 echo ""
 echo "           /     "
 echo "    \     /  /   Jose Nelson Amaral - jamaral@ualberta.ca"
 echo "     )   /  (    Professor"
 echo "    /   /    \   Dept. of Computing Science - University of Alberta"
 echo "   (   /      )  Edmonton, Alberta, Canada, T6G 2E8"
 echo "    \ O      /   Fax: (780)492-1071"
 echo "     \      /    http://www.cs.ualberta.ca/~amaral"
 echo "       ---- "
 echo "") | Mail -r "jamaral@ualberta.ca" -s "Blog de final de 2022" $ADDRESS
echo "mailed " $NAME:$ADDRESS
 done
